---
abstract: 'Plugin for production-tier access logging'
author:
  - 'Nic Sandfield <niczero@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Log-Access
no_index:
  directory:
    - t
    - inc
    - test
requires:
  Mojolicious: 3.33
  perl: 5.010001
resources:
  bugtracker: http://github.com/niczero/mojolicious-plugin-log-access/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/niczero/mojolicious-plugin-log-access
version: 0.021
